if ( GetLocale() == "zhCN" ) then

BINDING_HEADER_TOTEMTIMERSHEADER = "图腾计时器"
BINDING_NAME_TOTEMTIMERSEARTH    = "施放大地系图腾"
BINDING_NAME_TOTEMTIMERSAIR      = "施放空气系图腾"
BINDING_NAME_TOTEMTIMERSFIRE     = "施放火焰系图腾"
BINDING_NAME_TOTEMTIMERSWATER    = "施放水系图腾"
BINDING_NAME_TOTEMTIMERSEARTHMENU    = "打开大地系图腾菜单"
BINDING_NAME_TOTEMTIMERSAIRMENU      = "打开空气系图腾菜单"
BINDING_NAME_TOTEMTIMERSFIREMENU     = "打开火焰系图腾菜单"
BINDING_NAME_TOTEMTIMERSWATERMENU    = "打开水系图腾菜单"

BINDING_NAME_TOTEMTIMERSEARTHSHIELDFOCUS = "给焦点目标上大地盾"
BINDING_NAME_TOTEMTIMERSEARTHSHIELDTARGET = "给目标上大地盾"
BINDING_NAME_TOTEMTIMERSEARTHSHIELDSELF = "给自己上大地盾"
BINDING_NAME_TOTEMTIMERSWEAPONBUFF1 = "武器特效1"
BINDING_NAME_TOTEMTIMERSWEAPONBUFF2 = "武器特效2"

TT_DISEASE_CLEANSING = "祛病图腾"
TT_EARTHBIND = "地缚图腾"
TT_FIRE_NOVA = "火焰新星图腾"
TT_FIRE_RESISTANCE = "抗火图腾"
TT_FIRE_RESISTANCE_EFFECT = "火焰抗性"
TT_FROST_RESISTANCE	= "抗寒图腾"
TT_FROST_RESISTANCE_EFFECT = "冰霜抗性"
TT_FLAMETONGUE = "火舌图腾"
TT_GRACE_OF_AIR = "风之优雅图腾"
TT_GRACE_OF_AIR_EFFECT = "风之优雅"
TT_GROUNDING = "根基图腾"
TT_GROUNDING_EFFECT = "根基图腾效果"
TT_HEALING_STREAM = "治疗之泉图腾"
TT_HEALING_STREAM_EFFECT = "治疗之泉"
TT_MAGMA = "熔岩图腾"
TT_ANCIENT_MANA_SPRING = "上古法力之泉图腾"
TT_MANA_SPRING = "法力之泉图腾"
TT_MANA_SPRING_EFFECT = "法力之泉"
TT_MANA_TIDE = "法力之潮图腾"
TT_MANA_TIDE_EFFECT = "法力之潮"
TT_NATURE_RESISTANCE = "自然抗性图腾"
TT_NATURE_RESISTANCE_EFFECT = "自然抗性"
TT_POISON_CLEANSING = "清毒图腾"
TT_SEARING = "灼热图腾"
TT_SENTRY = "岗哨图腾"
TT_SENTRY_EFFECT = "岗哨图腾"
TT_STONECLAW = "石爪图腾"
TT_STONESKIN = "石肤图腾"
TT_STONESKIN_EFFECT = "石肤"
TT_STRENGTH_OF_EARTH = "大地之力图腾" 
TT_STRENGTH_OF_EARTH_EFFECT = "大地之力"
TT_TREMOR = "战栗图腾"
TT_TRANQUIL_AIR = "宁静之风图腾"
TT_TRANQUIL_AIR_EFFECT = "宁静之风"
TT_WINDFURY = "风怒图腾"
TT_WINDWALL = "风墙图腾"
TT_WINDWALL_EFFECT = "风墙"
TT_WRATH = "天怒图腾"
TT_WRATH_EFFECT = "天怒图腾"
TT_WRATH_AIR = "空气之怒图腾"
TT_WRATH_AIR_EFFECT = "空气之怒图腾"
TT_EARTH_ELEMENTAL = "土元素图腾"
TT_FIRE_ELEMENTAL = "火元素图腾"
TT_EARTH_ELE = "土元素"
TT_FIRE_ELE = "火元素"

TT_EARTH_ELEMENTAL_SHOUT = "召唤土元素，请求保护！"
TT_FIRE_ELEMENTAL_SHOUT = "召唤火元素，请求保护！"
TT_MANA_TIDE_SHOUT = "施放法力之潮！"

TT_TOTEMIC_CALL = "图腾召唤"
TT_REINCARNATION = "复生"
TT_LIGHTNING_SHIELD = "闪电之盾"
TT_WATER_SHIELD = "水之护盾"
TT_EARTH_SHIELD = "大地之盾"
TT_WINDFURY_WEAPON = "风怒武器"
TT_ROCKBITER_WEAPON = "石化武器"
TT_FLAMETONGUE_WEAPON = "火舌武器"
TT_FROSTBRAND_WEAPON = "冰封武器"

TT_EARTH = "大地图腾"
TT_AIR = "空气图腾"
TT_WATER = "水之图腾"
TT_FIRE = "火焰图腾"

TT_SHAMAN = "萨满祭司"

TT_RESET = "重置图腾计时器！"
TT_DESTROYED = "%s被摧毁了。"
TT_WARNING = "%s即将到期。"
TT_EXPIRED = "%s到期了。"
TT_SHIELDINACTIVE = "%s效果消失。"
TT_LOADED = "图腾计时器加载成功。"
TT_DEBUG = "调试信息"

TT_TOTEM = " [IV]+"

TT_COMBATLOG_TO_SPELL = {
	["风怒"] = "风怒武器",
	["石化"] = "石化武器",
	["火舌"] = "火舌武器",
	["冰封"] = "冰封武器",
	["风之宁静图腾"] = "宁静之风图腾",
}

end