if( GetLocale() == "zhCN" ) then

TT_GUI_HEADER = "TotemTimers"
TT_GUI_TAB_GENERAL = "基本设置"
TT_GUI_TAB_TIMERS = "计时器设置"
TT_GUI_TAB_TIMERS2 = "快捷键设置"
TT_GUI_TAB_TRACKERS = "追踪器设置"
TT_GUI_TAB_TRACKERS2 = "追踪器设置2"
TT_GUI_TAB_SHOUTS = "随身呼"
TT_GUI_TAB_MESSAGES = "消息提示"

TT_GUI_CHECKSHOW = "显示计时器"
TT_GUI_CHECKLOCK = "锁定计时器位置"
TT_GUI_CHECKEXPIRATIONWARNING = "到期警报"
TT_GUI_CHECKEXPIRATIONNOTIFICATION = "到期提示"
TT_GUI_CHECKDESTROYEDNOTIFICATION = "被摧毁提示"
TT_GUI_CHECKRECAST = "再次施放"
TT_GUI_CHECKFLASHRED = "红色闪动效果"
TT_GUI_CHECKPROCFLASH = "进度条"
TT_GUI_CHECKTOOLTIPS = "提示信息"
TT_GUI_CHECKMINIICONS = "微型图标"
TT_GUI_CHECKREINCARNATION = "复生计时器"
TT_GUI_CHECKMOUSEOVER = "鼠标停留展开"
TT_GUI_CHECKEARTHSHOUT = "召唤土元素的随身呼"
TT_GUI_CHECKFIRESHOUT = "召唤火元素的随身呼"
TT_GUI_CHECKMANASHOUT = "施放法力之潮的随身呼"
TT_GUI_CHECKSHOWTOTEMSASBUFFS = "在BUFF位置显示图腾计时"
TT_GUI_CHECKSHOWEARTHELEMENTALBUTTON = "显示土元素图腾"
TT_GUI_CHECKSHOWFIREELEMENTALBUTTON = "显示火元素图腾"
TT_GUI_CHECKSHOWMANATIDEBUTTON = "显示法力之潮图腾"
TT_GUI_CHECKTOTEMTWISTING = "显示风怒图腾作用计时"
TT_GUI_CHECKSWITCHAGIWF = "优雅与风怒图腾循环切换"
TT_GUI_CHECKDISABLEMENUDELAY = "禁止菜单延迟"

TT_GUI_TOOLTIPMOUSEOVER = "|cffffd100鼠标停留展开|r|n启用时，图腾按钮当鼠标移到计时器上就会展开(右键摧毁)，否则右键点击计时器时展开(中键摧毁)。" 
TT_GUI_TOOLTIPREINCARNATION = "|cffffd100复生冷却时间|r|n显示复生的技能冷却时间和携带的十字章数量。"
TT_GUI_TOOLTIPMINIICONS = "|cffffd100微型图标|r|n在图腾图标的右下角显示可以再次施放的图腾微型图标。"
TT_GUI_TOOLTIPTOOLTIPS = "|cffffd100提示信息|r|n当鼠标移到计时器或图标上时显示提示信息。"
TT_GUI_TOOLTIPPROCFLASH = "|cffffd100进度条|r|n在计时器中显示绿色的进度条。"
TT_GUI_TOOLTIPFLASHRED = "|cffffd100红色闪动效果|r|n启用的时候图腾即将过期时有红色闪动效果，否则是淡入淡出效果。"
TT_GUI_TOOLTIPRECAST = "|cffffd100再次施放|r|n启用再次施放机制。"
TT_GUI_TOOLTIPEARTHSHOUT = "|cffffd100召唤土元素的随身呼|r|n召唤土元素时发送一条通知， 如果在团队中就向整个团队发送,如果在队伍里就向队伍发送。"
TT_GUI_TOOLTIPFIRESHOUT = "|cffffd100召唤火元素的随身呼|r|n召唤火元素时发送一条通知， 如果在团队中就向整个团队发送,如果在队伍里就向队伍发送。"
TT_GUI_TOOLTIPMANASHOUT = "|cffffd100施放法力之潮的随身呼|r|n施放法力之潮是向队伍发送一条通知"
TT_GUI_TOOLTIPSHOWTOTEMSASBUFFS = "|cffffd100在BUFF位置显示图腾计时|r|n在BUFF框架上显示图腾计时。本功能需要重新载入UI。|n也许会由于你的某些插件导致这个功能不正常."
TT_GUI_TOOLTIPDISABLEMENUDELAY = "禁止当鼠标移开图腾按钮后菜单自动关闭的延迟"

TT_GUI_CHECKSHOWBAR = "显示计时条背景"
TT_GUI_CHECKREVERSEBARBINDINGS = "反转图腾快捷键"
TT_GUI_CHECKBARBINDINGS = "启用图腾快捷键"
TT_GUI_CHECKSHOWPARTYBUFFS = "显示图腾作用到的小队成员"
TT_GUI_CHECKSHOWPLAYERBUFFDOT = "在图腾图标上显示自己是否被作用到"

TT_GUI_TOOLTIPSHOWBAR = "在计时器时间下显示计时条背景"
TT_GUI_TOOLTIPREVERSEBARBINDINGS = "使快捷键顺序改为9-1|n"
	.."你必须重新登陆以使设置生效。"
TT_GUI_TOOLTIPBARBINDINGS = "如果启用，你可以在展开的图腾动作条上使用1-9快捷键|n"
	.."你必须重新登陆以使设置生效。" 

TT_GUI_DROPDOWN_ARRANGE = "排列"
TT_GUI_VERTICAL = "纵向"
TT_GUI_HORIZONTAL = "横向"
TT_GUI_BOX = "正方"
TT_GUI_FREE = "自由"

TT_GUI_DROPDOWN_STYLE = "样式"
TT_GUI_BUFF = "Buff"
TT_GUI_FIXED = "Fixed"
TT_GUI_ELEMENT = "Element"
TT_GUI_STICKY = "Sticky"

TT_GUI_SPACING = "间距"

TT_GUI_DROPDOWN_TIME = "时间样式"
TT_GUI_CT = "ct"
TT_GUI_BLIZZARD = "blizz"

TT_GUI_DROPDOWN_MSG = "消息样式"
TT_GUI_TT = "TotemTimers"
TT_GUI_SCT = "ScrollingCombatText"
TT_GUI_SCT2 = "ScrollingCombatText Crit"
TT_GUI_SCTMSG = "ScrollingCombatText Msg Frame"
TT_GUI_MSBT = "Mik's Scrolling Battle Text"
TT_GUI_PARROT = "Parrot"
TT_GUI_CHAT = "Chat frame messages"

TT_GUI_ORDER1 = "计时器1"
TT_GUI_ORDER2 = "计时器2"
TT_GUI_ORDER3 = "计时器3"
TT_GUI_ORDER4 = "计时器4"
TT_GUI_CHECKVISIBLE1 = "显示"
TT_GUI_CHECKVISIBLE2 = "显示"
TT_GUI_CHECKVISIBLE3 = "显示"
TT_GUI_CHECKVISIBLE4 = "显示"
TT_GUI_TIMERSIZE = "图标大小"
TT_GUI_TIMEHEIGHT = "时间大小"
TT_GUI_TRACKERSIZE = "图标大小"
TT_GUI_TRACKERTIMEHEIGHT = "时间大小"
TT_GUI_BARDIRECTION = "图腾动作条方向"

TT_GUI_AUTO = "自动"
TT_GUI_LEFT = "左侧"
TT_GUI_RIGHT = "右侧"
TT_GUI_UP = "上方"
TT_GUI_DOWN = "下方"
TT_GUI_TOP = "顶部"
TT_GUI_BOTTOM = "底部"

TT_GUI_DEBUG = "调试"
TT_GUI_RESET = "重置设置"
TT_GUI_RESETPOS = "缺省位置"

TT_GUI_CHECKSHIELDTRACKER = "显示盾追踪器"
TT_GUI_CHECKEARTHSHIELDTRACKER = "显示大地之盾追踪器"
TT_GUI_CHECKMAINENCHANT = "显示武器特效追踪器"
TT_GUI_CHECKSHIELDNOTIFICATION = "盾特效到期提示"
TT_GUI_CHECKEARTHSHIELDNOTIFICATION = "大地之盾提示"
TT_GUI_CHECKWEAPONNOTIFICATION = "武器特效提示"

TT_GUI_WEAPONBUFFLEFTCLICK = "主手([组合键]左键)"
TT_GUI_WEAPONBUFFRIGHTCLICK = "副手([组合键]右键)"
TT_GUI_WEAPONBUFFMODIFIER = "组合键"

TT_GUI_LEFTCLICK = "左键点击"
TT_GUI_RIGHTCLICK = "右键点击"
TT_GUI_MIDDLECLICK = "中键点击"
TT_GUI_BUTTON4CLICK = "鼠标按键4"

TT_GUI_SHIELDTRACKER = "盾追踪器"
TT_GUI_EARTHSHIELDTRACKER = "大地之盾追踪器"

TT_GUI_HIDE = "隐藏"

end