if( GetLocale() == "deDE" ) then

TT_GUI_HEADER = "TotemTimers"
TT_GUI_TAB_GENERAL = "Allgemein"
TT_GUI_TAB_TIMERS = "Timer 1"
TT_GUI_TAB_TIMERS = "Timer 2"
TT_GUI_TAB_TRACKERS = "Tracker"
TT_GUI_TAB_SHOUTS = "Rufen"
TT_GUI_TAB_MESSAGES = "Warnungen"

TT_GUI_CHECKSHOW = "Totemtimer anzeigen"
TT_GUI_CHECKLOCK = "Position fixieren"
TT_GUI_CHECKEXPIRATIONWARNING = "Vor Timerablauf warnen"
TT_GUI_CHECKEXPIRATIONNOTIFICATION = "Ausgelaufene Timer melden"
TT_GUI_CHECKDESTROYEDNOTIFICATION = "Zerstörte Totems melden"
TT_GUI_CHECKRECAST = "Recast einschalten"
TT_GUI_CHECKFLASHRED = "Rotes Leuchten"
TT_GUI_CHECKPROCFLASH = "Procleiste"
TT_GUI_CHECKTOOLTIPS = "Tooltips anzeigen"
TT_GUI_CHECKMINIICONS = "MiniIcons anzeigen"
TT_GUI_CHECKREINCARNATION = "Wiederbelebungstimer anzeigen"
TT_GUI_CHECKMOUSEOVER = "Mouseover"
TT_GUI_CHECKEARTHSHOUT = "Erdelementar im Chat ausrufen"
TT_GUI_CHECKFIRESHOUT = "Feuerelementar im Chat ausrufen"
TT_GUI_CHECKMANASHOUT = "Manaflut im Chat ausrufen"
TT_GUI_CHECKSHOWTOTEMSASBUFFS = "Timer als Buff anzeigen"
TT_GUI_CHECKSHOWEARTHELEMENTALBUTTON = "Erdele anzeigen"
TT_GUI_CHECKSHOWFIREELEMENTALBUTTON = "Feuerele anzeigen"
TT_GUI_CHECKSHOWMANATIDEBUTTON = "Manaflut anzeigen"
TT_GUI_CHECKDISABLEMENUDELAY = "Menüverzögerung ausschalten"
TT_GUI_CHECKFOCUSELEMENTALS = "Elementare in Fokus"
TT_GUI_CHECKCOLORTIMERBARS = "Timer einfärben"
TT_GUI_CHECKHIDEBLIZZARDTIMERS = "Blizzards Timer ausschalten"

TT_GUI_TOOLTIPMOUSEOVER = "|cffffd100Mouseover|r|nWenn eingeschaltet, werden die Totems angezeigt, sobald du mit der Maus über einen Timer fährst, ansonsten auf Rechtsklick." 
TT_GUI_TOOLTIPREINCARNATION = "|cffffd100Wiederbelebungstimer|r|nZeigt den Cooldown deiner Reinkarnation an sowie die Anzahl der Ankhs in deiner Tasche."
TT_GUI_TOOLTIPMINIICONS = "|cffffd100Miniicons|r|nAnzeigen der kleinen Icons unten rechts in den Timern, die angeben, welches Totem bei Klick auf den Timer gestellt wird."
TT_GUI_TOOLTIPTOOLTIPS = "|cffffd100Tooltips|r|nTooltips werden angezeigt, sobald du mit der Maus über einen Timer oder einen Totemknopf fährst."
TT_GUI_TOOLTIPPROCFLASH = "|cffffd100Procleiste|r|nZeigt einen grünen Balken innerhalb eines Timers an, der voll ist, sobald das Totem seinen Effekt auslöst."
TT_GUI_TOOLTIPFLASHRED = "|cffffd100Rotes Leuchten|r|nEingeschaltet blinken Timer kurz vor verschwinden des Totems rot auf, ansonsten blinken sie durchsichtig."
TT_GUI_TOOLTIPRECAST = "|cffffd100Recast|r|nSchaltet den Recastmechanismus ein (die Möglichkeit, mit den Timerknöpfen Totems zu stellen)."
TT_GUI_TOOLTIPEARTHSHOUT = "|cffffd100Erdelementar im Chat ausrufen|r|nWenn du dein Erdelementar stellst, wird eine Nachricht im Raidchat gepostet bzw. im Gruppenchat, falls du keinem Raid angehörst."
TT_GUI_TOOLTIPFIRESHOUT = "|cffffd100Feuerelementar im Chat ausrufen|r|nWenn du dein Feuerelementar stellst, wird eine Nachricht im Raidchat gepostet bzw. im Gruppenchat, falls du keinem Raid angehörst."
TT_GUI_TOOLTIPMANASHOUT = "|cffffd100Manaflut im Chat ausrufen|r|nWenn du dein Manaflut stellst, wird eine Nachricht im Gruppenchat gepostet."
TT_GUI_TOOLTIPSHOWTOTEMSASBUFFS = "|cffffd100Timer als Buff anzeigen|r|nZeigt die Totemtimer als gewöhnlichen Buff im Buffframe.|nBenötigt Neuladen des UIs.|nFunktioniert nicht mit allen Addons zusammen."
TT_GUI_TOOLTIPDISABLEMENUDELAY = "Schaltet die Verzögerung zwischen Verlassen eines Knopfs und Schließen seines Menüs aus"
TT_GUI_TOOLTIPFOCUSELEMENTALS = "|cffffd100Elementare in Fokus|r|nWenn aktiviert, setzt bei einem zweiten Klick auf die entsprechenden Knöpfe|ndie herbeigezauberten Elementare als Fokus.|nBenötigt einen Relog oder Neuladens des UI zum aktivieren."
TT_GUI_TOOLTIPCOLORTIMERBARS = "|cffffd100Timer einfärben|r|Färbt die Timer passend zum Element des Timers."

TT_GUI_TIMEFONT = "Zeit-Schriftart"

TT_GUI_CHECKSHOWBAR = "Timer bars anzeigen"
TT_GUI_CHECKREVERSEBARBINDINGS = "Totemnumerierung umkehren"
TT_GUI_CHECKBARBINDINGS = "Keybindings für Totems"
TT_GUI_CHECKSHOWPARTYBUFFS = "Totembuffs der Gruppe"
TT_GUI_CHECKSHOWPLAYERBUFFDOT = "Spielerbuff anzeigen"

TT_GUI_TOOLTIPSHOWBAR = "Die Zeitanzeigen der Totems werden mit graphischen Bars unterlegt"
TT_GUI_TOOLTIPREVERSEBARBINDINGS = "Die Totems in den Menüs werden von 9-1 nummeriert anstatt von 1-9.|n"
	.."Wird erst nach dem nächsten Login übernommen."
TT_GUI_TOOLTIPBARBINDINGS = "Die Totems in den Menüs können bei Anzeige mit den Tasten 1-9 gestellt werden|n"
	.."Wird erst nach dem nächsten Login übernommen." 
	
TT_GUI_DROPDOWN_ARRANGE = "Anordnung"
TT_GUI_VERTICAL = "vertikal"
TT_GUI_HORIZONTAL = "horizontal"
TT_GUI_BOX = "box"
TT_GUI_FREE = "free"

TT_GUI_DROPDOWN_STYLE = "Timer-Stil"
TT_GUI_BUFF = "Buff"
TT_GUI_FIXED = "Fixed"
TT_GUI_ELEMENT = "Element"
TT_GUI_STICKY = "Sticky"

TT_GUI_SPACING = "Abstand"
TT_GUI_TIMESPACING = "Zeitabstand"
TT_GUI_TRACKERSPACING = TT_GUI_SPACING
TT_GUI_TRACKERTIMESPACING = TT_GUI_TIMESPACING

TT_GUI_DROPDOWN_TIME = "Zeitstil"
TT_GUI_CT = "ct"
TT_GUI_BLIZZARD = "blizz"

TT_GUI_DROPDOWN_TIMEPOS = "Zeit-Position"
TT_GUI_DROPDOWN_TRACKERTIMEPOS = TT_GUI_DROPDOWN_TIMEPOS

TT_GUI_DROPDOWN_MSG = "Nachrichtenanzeige"
TT_GUI_TT = "TotemTimers"
TT_GUI_SCT = "ScrollingCombatText"
TT_GUI_MSBT = "Mik's Scrolling Battle Text"
TT_GUI_CHAT = "Chatfenster"

TT_GUI_ORDER1 = "Timerknopf 1"
TT_GUI_ORDER2 = "Timerknopf 2"
TT_GUI_ORDER3 = "Timerknopf 3"
TT_GUI_ORDER4 = "Timerknopf 4"
TT_GUI_CHECKVISIBLE1 = "anzeigen"
TT_GUI_CHECKVISIBLE2 = "anzeigen"
TT_GUI_CHECKVISIBLE3 = "anzeigen"
TT_GUI_CHECKVISIBLE4 = "anzeigen"
TT_GUI_TIMERSIZE = "Buttongröße"
TT_GUI_TIMEHEIGHT = "Zeitgröße"
TT_GUI_TRACKERSIZE = "Trackergröße"
TT_GUI_TRACKERTIMEHEIGHT = "Trackerzeit-Größe"

TT_GUI_AUTO = "auto"
TT_GUI_LEFT = "links"
TT_GUI_RIGHT = "rechts"
TT_GUI_UP = "hoch"
TT_GUI_DOWN = "runter"
TT_GUI_TOP = "oben"
TT_GUI_BOTTOM = "runter"

TT_GUI_DEBUG = "Debug"
TT_GUI_RESET = "Alles zurücksetzen"
TT_GUI_RESETPOS = "Position zurücksetzen"

TT_GUI_CHECKSHIELDTRACKER = "Zeige Schild-Tracker"
TT_GUI_CHECKEARTHSHIELDTRACKER = "Zeige Erdschild-Tracker"
TT_GUI_CHECKMAINENCHANT = "Zeige Waffenbuff-Tracker"
TT_GUI_CHECKSHIELDNOTIFICATION = "Schildwarnungen"
TT_GUI_CHECKEARTHSHIELDNOTIFICATION = "Erdschildwarnungen"
TT_GUI_CHECKWEAPONNOTIFICATION = "Waffen-Buff-Warnungen"

TT_GUI_WEAPONBUFFLEFTCLICK = "Waffentracker LK"
TT_GUI_WEAPONBUFFRIGHTCLICK = "Waffentracker RK"
TT_GUI_WEAPONBUFFMODIFIER = "Zweitbelegungstaste"
end