if( GetLocale() == "zhTW" ) then

TT_GUI_HEADER = "TotemTimers"
TT_GUI_TAB_GENERAL = "綜合"
TT_GUI_TAB_TIMERS = "圖騰"
TT_GUI_TAB_TIMERS2 = "快捷鍵設置"
TT_GUI_TAB_TRACKERS = "追蹤"
TT_GUI_TAB_SHOUTS = "喊話"
TT_GUI_TAB_MESSAGES = "消息提示"

TT_GUI_CHECKSHOW = "顯示圖騰計時器"
TT_GUI_CHECKLOCK = "鎖定計時器位置"
TT_GUI_CHECKEXPIRATIONWARNING = "顯示圖騰即將消失警告"
TT_GUI_CHECKEXPIRATIONNOTIFICATION = "顯示圖騰結束提示"
TT_GUI_CHECKDESTROYEDNOTIFICATION = "顯示圖騰被摧毀信息"
TT_GUI_CHECKRECAST = "啟用重復施法"
TT_GUI_CHECKFLASHRED = "紅色閃爍"
TT_GUI_CHECKPROCFLASH = "啟用圖騰作用條"
TT_GUI_CHECKTOOLTIPS = "顯示提示信息"
TT_GUI_CHECKMINIICONS = "顯示小圖標"
TT_GUI_CHECKREINCARNATION = "復生倒計時"
TT_GUI_CHECKMOUSEOVER = "滑鼠浮動"
TT_GUI_CHECKEARTHSHOUT = "施放土元素圖騰時喊話"
TT_GUI_CHECKFIRESHOUT = "施放火元素圖騰時喊話"
TT_GUI_CHECKMANASHOUT = "施放法力之潮圖騰時喊話"
TT_GUI_CHECKSHOWTOTEMSASBUFFS = "在BUFF位置顯示圖騰計時"
TT_GUI_CHECKSHOWEARTHELEMENTALBUTTON = "顯示土元素圖騰"
TT_GUI_CHECKSHOWFIREELEMENTALBUTTON = "顯示火元素圖騰"
TT_GUI_CHECKSHOWMANATIDEBUTTON = "顯示法力之潮圖騰"
TT_GUI_CHECKTOTEMTWISTING = "顯示風怒圖騰作用計時"

TT_GUI_TOOLTIPMOUSEOVER = "|cffffd100滑鼠浮動|r|n若啟用該項則當您將滑鼠指向某按鈕時顯示該技能說明，否則僅在您右鍵點擊時顯示。" 
TT_GUI_TOOLTIPREINCARNATION = "|cffffd100復生效果計時器|r|n顯示您的復生效果冷卻時間及所攜帶的十字章數量。"
TT_GUI_TOOLTIPMINIICONS = "|cffffd100小圖標|r|n在圖騰按鈕的右下方顯示一小圖騰圖標，該圖騰技能將被再次施放。"
TT_GUI_TOOLTIPTOOLTIPS = "|cffffd100提示信息|r|n當您將滑鼠移至計時條或圖騰按鈕時將顯示技能提示信息。"
TT_GUI_TOOLTIPPROCFLASH = "|cffffd100作用條|r|n以一個綠色進度條顯示圖騰每次作用的間隔過程。"
TT_GUI_TOOLTIPFLASHRED = "|cffffd100紅色閃爍|r|n圖騰或技能即將結束的最后10秒內，該計時圖標會以紅色閃爍。"
TT_GUI_TOOLTIPRECAST = "|cffffd100重復施法|r|n啟用重復施法功能。"
TT_GUI_TOOLTIPEARTHSHOUT = "|cffffd100施放土元素圖騰時喊話|r|n當您施放土元素圖騰時，將向團隊頻道(若您在團隊中)或隊伍頻道(若您不在團隊中)發送如下消息。"
TT_GUI_TOOLTIPFIRESHOUT = "|cffffd100施放火元素圖騰時喊話|r|n當您施放火元素圖騰時，將向團隊頻道(若您在團隊中)或隊伍頻道(若您不在團隊中)發送如下消息。"
TT_GUI_TOOLTIPMANASHOUT = "|cffffd100施放法力之潮圖騰時喊話|r|n當您施放法力之潮時，將向隊伍頻道發送如下消息。"
TT_GUI_TOOLTIPSHOWTOTEMSASBUFFS = "|cffffd100在BUFF位置顯示圖騰計時|r|n在BUFF框架上顯示圖騰計時。本功能需要重新載入ui。|nMay not work depending on what addons you use."

TT_GUI_CHECKSHOWBAR = "顯示時間條"
TT_GUI_CHECKREVERSEBARBINDINGS = "顛倒圖騰按鍵條"
TT_GUI_CHECKBARBINDINGS = "允許圖騰按鍵條"
TT_GUI_CHECKSHOWPARTYBUFFS = "顯示圖騰buff作用到的小隊成員"

TT_GUI_TOOLTIPSHOWBAR = "顯示時間條在數字之下"
TT_GUI_TOOLTIPREVERSEBARBINDINGS = "綁定按鍵 9-1 在圖騰菜單中代替 1-9|n "
	.."你需要重新載入這個設置才能生效."
TT_GUI_TOOLTIPBARBINDINGS = "如果可以, 圖騰按鍵將映射到 1-9 to 在圖騰菜單顯示的情況下|n"
	.."你需要重新載入這個設置才能生效." 

TT_GUI_DROPDOWN_ARRANGE = "排列方式"
TT_GUI_VERTICAL = "豎直方向"
TT_GUI_HORIZONTAL = "水平方向"
TT_GUI_BOX = "方格排列"
TT_GUI_FREE = "自由排列"

TT_GUI_DROPDOWN_STYLE = "圖標風格"
TT_GUI_BUFF = "Buff"
TT_GUI_FIXED = "增益樣式"
TT_GUI_ELEMENT = "圖騰樣式"
TT_GUI_STICKY = "按鈕樣式"

TT_GUI_DROPDOWN_TIME = "計時風格"
TT_GUI_CT = "CT(MM:SS)"
TT_GUI_BLIZZARD = "系統(SS秒)"

TT_GUI_DROPDOWN_MSG = "消息風格"
TT_GUI_TT = "TotemTimers"
TT_GUI_SCT = "浮動戰斗文字"
TT_GUI_MSBT = "Mik's SBT"
TT_GUI_PARROT = "Parrot"
TT_GUI_CHAT = "Chat frame messages"

TT_GUI_ORDER1 = "圖騰按鈕一"
TT_GUI_ORDER2 = "圖騰按鈕二"
TT_GUI_ORDER3 = "圖騰按鈕三"
TT_GUI_ORDER4 = "圖騰按鈕四"
TT_GUI_CHECKVISIBLE1 = "啟用"
TT_GUI_CHECKVISIBLE2 = "啟用"
TT_GUI_CHECKVISIBLE3 = "啟用"
TT_GUI_CHECKVISIBLE4 = "啟用"
TT_GUI_TIMERSIZE = "圖騰按鈕大小"
TT_GUI_TIMEHEIGHT = "計時文字大小"
TT_GUI_TRACKERSIZE = "增益按鈕大小"
TT_GUI_TRACKERTIMEHEIGHT = "計時文字大小"
TT_GUI_BARDIRECTION = "圖騰菜單方向"

TT_GUI_AUTO = "自動"
TT_GUI_LEFT = "左"
TT_GUI_RIGHT = "右"
TT_GUI_UP = "上"
TT_GUI_DOWN = "下"
TT_GUI_TOP = "最頂"
TT_GUI_BOTTOM = "底部"

TT_GUI_DEBUG = "調試"
TT_GUI_RESET = "全部重置"
TT_GUI_RESETPOS = "重置位置"

TT_GUI_CHECKSHIELDTRACKER = "盾追蹤器"
TT_GUI_CHECKEARTHSHIELDTRACKER = "大地之盾追蹤器"
TT_GUI_CHECKMAINENCHANT = "武器特殊效果計時器"
TT_GUI_CHECKSHIELDNOTIFICATION = "追蹤魔法盾效果"
TT_GUI_CHECKEARTHSHIELDNOTIFICATION = "追蹤大地之盾效果"
TT_GUI_CHECKWEAPONNOTIFICATION = "追蹤武器增益效果"

TT_GUI_WEAPONBUFFLEFTCLICK = "武器增益左鍵點擊"
TT_GUI_WEAPONBUFFRIGHTCLICK = "武器增益右鍵點擊"
TT_GUI_WEAPONBUFFMODIFIER = "組合鍵"

end
