TT_GUI_HEADER = "TotemTimers"
TT_GUI_TAB_GENERAL = "General"
TT_GUI_TAB_TIMERS = "Timers 1"
TT_GUI_TAB_TIMERS2 = "Timers 2"
TT_GUI_TAB_TRACKERS = "Trackers"
TT_GUI_TAB_TRACKERS2 = "Trackers 2"
TT_GUI_TAB_SHOUTS = "Shouts"
TT_GUI_TAB_MESSAGES = "Messages"

TT_GUI_CHECKSHOW = "Show totem timers"
TT_GUI_CHECKLOCK = "Lock timers' position"
TT_GUI_CHECKEXPIRATIONWARNING = "Show expiration warnings"
TT_GUI_CHECKEXPIRATIONNOTIFICATION = "Show expiration notifications"
TT_GUI_CHECKDESTROYEDNOTIFICATION = "Show destruction notifications"
TT_GUI_CHECKRECAST = "Enable Recasting"
TT_GUI_CHECKFLASHRED = "Red flash color"
TT_GUI_CHECKPROCFLASH = "Enable proc bar"
TT_GUI_CHECKTOOLTIPS = "Show tooltips"
TT_GUI_CHECKMINIICONS = "Show mini icons"
TT_GUI_CHECKREINCARNATION = "Show reincarnation timer"
TT_GUI_CHECKMOUSEOVER = "Mouseover"
TT_GUI_CHECKEARTHSHOUT = "Shout Earth Elemental cast"
TT_GUI_CHECKFIRESHOUT = "Shout Fire Elemental cast"
TT_GUI_CHECKMANASHOUT = "Shout Mana Tide Totem cast"
TT_GUI_CHECKSHOWTOTEMSASBUFFS = "Show timers as buffs"
TT_GUI_CHECKSHOWEARTHELEMENTALBUTTON = "Show Earth Elemental"
TT_GUI_CHECKSHOWFIREELEMENTALBUTTON = "Show Fire Elemental"
TT_GUI_CHECKSHOWMANATIDEBUTTON = "Show Mana Tide Totem"
TT_GUI_CHECKTOTEMTWISTING = "Totem Twisting timer"
TT_GUI_CHECKSWITCHAGIWF = "Rotate agi/wf totems"
TT_GUI_CHECKDISABLEMENUDELAY = "Disable menu delay"
TT_GUI_CHECKFOCUSELEMENTALS = "Focus elementals"
TT_GUI_CHECKCOLORTIMERBARS = "Color Timer Bars"
TT_GUI_CHECKHIDEBLIZZTIMERS = "Hide Blizzard Timers"

TT_GUI_TOOLTIPMOUSEOVER = "|cffffd100Mouseover|r|nIf enabled totem buttons will be shown if you mouseover a timer, else they will be shown on rightclick." 
TT_GUI_TOOLTIPREINCARNATION = "|cffffd100Reincarnation timer|r|nShows the remaining cooldown of your reincarnation ability as well as the number of ankhs in your bags."
TT_GUI_TOOLTIPMINIICONS = "|cffffd100Mini Icons|r|nShows the small icons in the lower right of the timer buttons which indicate the totem the button will recast."
TT_GUI_TOOLTIPTOOLTIPS = "|cffffd100Tooltips|r|nShows tooltips if you mouseover the timer or totem buttons."
TT_GUI_TOOLTIPPROCFLASH = "|cffffd100Proc Bar|r|nShows a green status bar inside the timers that fills until a totem procs."
TT_GUI_TOOLTIPFLASHRED = "|cffffd100Red Flash|r|nIf enabled expiring totems flash red, else they will fade in and out."
TT_GUI_TOOLTIPRECAST = "|cffffd100Recasting|r|nEnable the recasting mechanism."
TT_GUI_TOOLTIPEARTHSHOUT = "|cffffd100Shout Earth Elemental cast|r|nIf you cast your Earth Elemental, you will post a message into the raid chat ord the group chat if you are not in a raid."
TT_GUI_TOOLTIPFIRESHOUT = "|cffffd100Shout Fire Elemental cast|r|nIf you cast your Fire Elemental, you will post a message into the raid chat ord the group chat if you are not in a raid."
TT_GUI_TOOLTIPMANASHOUT = "|cffffd100Shout Mana Tide Totem cast|r|nIf you cast your Mana Tide Totem you will post a message into the group chat."
TT_GUI_TOOLTIPSHOWTOTEMSASBUFFS = "|cffffd100Show timers as buffs|r|nShows the timers in the buff frame. Needs a reload of the ui.|nMay not work depending on what addons you use."
TT_GUI_TOOLTIPDISABLEMENUDELAY = "Disables the menu closing delay when leaving a timer button"
TT_GUI_TOOLTIPFOCUSELEMENTALS = "|cffffd100Focus elementals|r|nIf enabled a second click on the elemental buttons will focus the cast elemental.|nWill need a relog or reloading the UI to activate."
TT_GUI_TOOLTIPCOLORTIMERBARS = "|cffffd100Color Timer Bars|r|Color Timer Bars according to their elements."

TT_GUI_TIMEFONT = "Time Font"
TT_GUI_TIMERBARTEXTURE = "Timer Bar Texture"

TT_GUI_CHECKSHOWBAR = "Show timer bars"
TT_GUI_CHECKREVERSEBARBINDINGS = "Reverse totem key bindings"
TT_GUI_CHECKBARBINDINGS = "Enable totem bar key bindings"
TT_GUI_CHECKSHOWPARTYBUFFS = "Show Party Totem Buffs"
TT_GUI_CHECKSHOWPLAYERBUFFDOT = "Show Player Buff dot"

TT_GUI_TOOLTIPSHOWBAR = "Show graphical timer bars underneath the numeric time display"
TT_GUI_TOOLTIPREVERSEBARBINDINGS = "Bind keys in order 9-1 to totems in totem menus instead of 1-9|n"
	.."You have to relog for this setting to take effect."
TT_GUI_TOOLTIPBARBINDINGS = "If enabled, totem buttons will have mapped the key 1-9 to them if totem menus are shown|n"
	.."You have to relog for this setting to take effect." 

TT_GUI_DROPDOWN_ARRANGE = "Arrangement"
TT_GUI_VERTICAL = "vertical"
TT_GUI_HORIZONTAL = "horizontal"
TT_GUI_BOX = "box"
TT_GUI_FREE = "free"

TT_GUI_DROPDOWN_STYLE = "Style"
TT_GUI_BUFF = "Buff"
TT_GUI_FIXED = "Fixed"
TT_GUI_ELEMENT = "Element"
TT_GUI_STICKY = "Sticky"

TT_GUI_SPACING = "Spacing"
TT_GUI_TIMESPACING = "Time Spacing"
TT_GUI_TRACKERSPACING = TT_GUI_SPACING
TT_GUI_TRACKERTIMESPACING = TT_GUI_TIMESPACING

TT_GUI_DROPDOWN_TIME = "Time style"
TT_GUI_CT = "ct"
TT_GUI_BLIZZARD = "blizz"

TT_GUI_DROPDOWN_TIMEPOS = "Timer Bar Position"
TT_GUI_DROPDOWN_TRACKERTIMEPOS = TT_GUI_DROPDOWN_TIMEPOS

TT_GUI_DROPDOWN_MSG = "Msg style"
TT_GUI_TT = "TotemTimers"
TT_GUI_SCT = "ScrollingCombatText"
TT_GUI_SCT2 = "ScrollingCombatText Crit"
TT_GUI_SCTMSG = "ScrollingCombatText Msg Frame"
TT_GUI_MSBT = "Mik's Scrolling Battle Text"
TT_GUI_PARROT = "Parrot"
TT_GUI_CHAT = "Chat frame messages"

TT_GUI_ORDER1 = "Timer Button 1"
TT_GUI_ORDER2 = "Timer Button 2"
TT_GUI_ORDER3 = "Timer Button 3"
TT_GUI_ORDER4 = "Timer Button 4"
TT_GUI_CHECKVISIBLE1 = "visible"
TT_GUI_CHECKVISIBLE2 = "visible"
TT_GUI_CHECKVISIBLE3 = "visible"
TT_GUI_CHECKVISIBLE4 = "visible"
TT_GUI_TIMERSIZE = "Button Size"
TT_GUI_TIMEHEIGHT = "Time Size"
TT_GUI_TRACKERSIZE = "Tracker Button Size"
TT_GUI_TRACKERTIMEHEIGHT = "Tracker Time Size"
TT_GUI_BARDIRECTION = "Totem menu direction"

TT_GUI_AUTO = "auto"
TT_GUI_LEFT = "left"
TT_GUI_RIGHT = "right"
TT_GUI_UP = "up"
TT_GUI_DOWN = "down"
TT_GUI_TOP = "top"
TT_GUI_BOTTOM = "bottom"

TT_GUI_DEBUG = "Debug"
TT_GUI_RESET = "Reset all"
TT_GUI_RESETPOS = "Reset position"

TT_GUI_CHECKSHIELDTRACKER = "Show Shield Tracker"
TT_GUI_CHECKEARTHSHIELDTRACKER = "Show Earth Shield Tracker"
TT_GUI_CHECKMAINENCHANT = "Show Weapon Buff Tracker"
TT_GUI_CHECKSHIELDNOTIFICATION = "Shield expiration warnings"
TT_GUI_CHECKEARTHSHIELDNOTIFICATION = "EarthShield warnings"
TT_GUI_CHECKWEAPONNOTIFICATION = "Weapon buff warnings"

TT_GUI_WEAPONBUFFLEFTCLICK = "Weapon Tracker LC/Shift-LC"
TT_GUI_WEAPONBUFFRIGHTCLICK = "Weapon Tracker RC/Shift-RC"
TT_GUI_WEAPONBUFFMODIFIER = "Modifier key"

TT_GUI_LEFTCLICK = "Leftclick"
TT_GUI_RIGHTCLICK = "Rightclick"
TT_GUI_MIDDLECLICK = "Middle Button"
TT_GUI_BUTTON4CLICK = "Button 4"

TT_GUI_SHIELDTRACKER = "Shield Tracker"
TT_GUI_EARTHSHIELDTRACKER = "Earth Shield Tracker"

TT_GUI_HIDE = "hide"